### ISSUE TITLE
Fan curve editor renders curve outside of visiable area when fractional scaling is enabled on gnome

### ISSUE THREAD

**Issue by nilsherzig** [AaronErhardt/tuxedo-rs#63] opened 2024-02-08 23:11 UTC
[Screencast from 2024-02-09 00-08-51.webm](https://github.com/AaronErhardt/tuxedo-rs/assets/72463901/f7978f0f-b432-47aa-9ddb-096ec8d7391f)

I think the video shows the problem better, than i could explain it :)

**Comment by AaronErhardt** [comment] 2024-02-09 07:02
Hi Nils,
thanks for the report.
The issue is already fixed on the main branch, but not released yet. See #46 for more information.

**Comment by nilsherzig** [comment] 2024-02-10 09:09
Oh sorry, i thought i checked every related issue. Thanks for the great work :)

**Closed** 2024-02-10 09:09 UTC
